version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: pokemon-back/Dockerfile
    container_name: pokemon-symfony-back
    ports:
      - "8081:80"
    volumes:
      - ./pokemon-back:/var/www/html:delegated
      - ./pokemon-back/var:/var/www/html/var:rw
    networks:
      - pokemon-network
    environment:
      - SYMFONY_ENV=dev
    command: >
      bash -c "rm -rf var/cache/* && apache2-foreground"

networks:
  pokemon-network:
    driver: bridge
