version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: pokemon-back/Dockerfile
    container_name: pokemon-symfony-back
    ports:
      - "8081:80"
    volumes:
      - ./pokemon-back:/var/www/html
    networks:
      - pokemon-network
    environment:
      - SYMFONY_ENV=dev

  react:
    build:
      context: .
      dockerfile: pokemon-react/Dockerfile
    container_name: pokemon-symfony-react
    ports:
      - "3000:3000"
    volumes:
      - ./pokemon-react:/app
      - /app/node_modules  # Pour éviter les conflits entre les node_modules locaux et ceux du conteneur
    networks:
      - pokemon-network
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

networks:
  pokemon-network:
    driver: bridge
