version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: pokemon-back/Dockerfile
    container_name: pokemon-symfony-back
    ports:
      - "8081:80"
    volumes:
      - ./pokemon-back:/var/www/html
    networks:
      - pokemon-network
    environment:
      - SYMFONY_ENV=dev

networks:
  pokemon-network:
    driver: bridge
